/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package book;


import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author Mizanur Rahman
 */
public class BookOperation extends javax.swing.JFrame {

    /** Creates new form BookOperation */
    public BookOperation() {
        initComponents();
        txtbid.setText(""+autoid());
        datashowCombo();
        String m="SELECT `bname`,`author`,`publisher`,`catagory`,`language`,`price`,`quantity` FROM `book`";
        showData(m);
    }
    
    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    
    
 
    
   
    void Myconnect(){
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost/javalibrary","root","");
            st=con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(BookOperation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
   int autoid(){
        int a=0;
        try {
            Myconnect();
            String m="SELECT `bid` FROM `book` ORDER BY `bid` ASC";
           rs=st.executeQuery(m);
           while(rs.next()){
               a=rs.getInt(1);
           }
           a++;
           
            
        } catch (SQLException ex) {
            Logger.getLogger(BookOperation.class.getName()).log(Level.SEVERE, null, ex);
        }
      return a;  
    }
   
   void datashowCombo(){
        try {
            txtcatagory.removeAllItems();
            txtcatagory.addItem("");
            String m="SELECT `catagory` FROM `book_catagory`";
            rs=st.executeQuery(m);
            while(rs.next()){
                txtcatagory.addItem(rs.getString(1));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(BookOperation.class.getName()).log(Level.SEVERE, null, ex);
        }
   }
   
   void showData(String m){
        try {
            int a=0;
            DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
            dt.setRowCount(0);
            rs=st.executeQuery(m);
            while(rs.next()){
                 dt.addRow(new Object[]{a++,rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)});
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(BookOperation.class.getName()).log(Level.SEVERE, null, ex);
        }
   }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtquant = new javax.swing.JTextField();
        txtpublisher = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        bname = new javax.swing.JTextField();
        txtauthor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtbid = new javax.swing.JTextField();
        txtcatagory = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtlanguage = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 102));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Books Info"));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);
        jPanel1.add(txtquant);
        txtquant.setBounds(170, 380, 280, 40);
        jPanel1.add(txtpublisher);
        txtpublisher.setBounds(170, 180, 280, 40);

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtprice);
        txtprice.setBounds(170, 330, 280, 40);

        bname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnameActionPerformed(evt);
            }
        });
        jPanel1.add(bname);
        bname.setBounds(170, 80, 280, 40);

        txtauthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtauthorActionPerformed(evt);
            }
        });
        jPanel1.add(txtauthor);
        txtauthor.setBounds(170, 130, 280, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Author name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 130, 130, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Publisher");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 180, 130, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Price");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 330, 130, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Book name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 80, 130, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Book ID");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(80, 30, 130, 40);

        txtbid.setFocusable(false);
        txtbid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbidActionPerformed(evt);
            }
        });
        jPanel1.add(txtbid);
        txtbid.setBounds(170, 30, 280, 40);

        txtcatagory.setEditable(true);
        txtcatagory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcatagoryKeyPressed(evt);
            }
        });
        jPanel1.add(txtcatagory);
        txtcatagory.setBounds(170, 230, 230, 40);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Quantity");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(80, 380, 130, 40);

        jButton2.setText("save");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(30, 450, 100, 30);

        jButton3.setText("edit");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton3);
        jButton3.setBounds(140, 450, 110, 30);

        jButton4.setBackground(new java.awt.Color(204, 0, 51));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("delete");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton4);
        jButton4.setBounds(260, 450, 110, 30);

        jButton5.setText("clear");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton5);
        jButton5.setBounds(390, 450, 90, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Language");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(80, 280, 130, 40);

        txtlanguage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bangla", "English" }));
        jPanel1.add(txtlanguage);
        txtlanguage.setBounds(170, 280, 280, 40);

        jLabel12.setText("Catagory");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(80, 230, 80, 30);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinfo/picture/icons8_checked_32px.png"))); // NOI18N
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(400, 230, 50, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 70, 500, 530);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinfo/picture/icons8_close_window_32px.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1270, 0, 32, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SL", "Book name", "Author name", "Publisher", "Language", "Price", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(550, 80, 710, 520);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Book Info");
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(450, 20, 330, 30);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(1000, 40, 210, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinfo/picture/icons8_checked_32px.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton1);
        jButton1.setBounds(1210, 40, 50, 30);

        setSize(new java.awt.Dimension(1303, 611));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void bnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnameActionPerformed

    private void txtauthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtauthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtauthorActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void txtbidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbidActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String id=txtbid.getText().toString();
        String name=bname.getText().toString();
        String author=txtauthor.getText().toString();
        String publisher=txtpublisher.getText().toString();
        String catagory=txtcatagory.getSelectedItem().toString();
        String price=txtprice.getText().toString();
        String quant=txtquant.getText().toString();
        String language=txtlanguage.getSelectedItem().toString();
        
        if (name.isEmpty()) {
            bname.requestFocus();
            JOptionPane.showMessageDialog(this, "book name is empty");
        }
           else if (author.isEmpty()) {
            bname.requestFocus();
            JOptionPane.showMessageDialog(this, "book name is empty");
        }
            else if (publisher.isEmpty()) {
            bname.requestFocus();
            JOptionPane.showMessageDialog(this, "book name is empty");
        }
            else if (catagory.isEmpty()) {
            txtprice.requestFocus();
            JOptionPane.showMessageDialog(this, "book catagory is empty");
        }
         
            else if(price.isEmpty()) {
            txtprice.requestFocus();
            JOptionPane.showMessageDialog(this, "book price is empty");
        }
         
            else if (quant.isEmpty()) {
            txtquant.requestFocus();
            JOptionPane.showMessageDialog(this, "book quant is empty");
            }
            else if (language.isEmpty()) {
            txtlanguage.requestFocus();
            JOptionPane.showMessageDialog(this, "language is empty");
        }
             else{
                try {
                    String m="INSERT INTO `book`(`bname`,`author`,`publisher`,`catagory`,`language`,`price`,`quantity`) VALUES ('"+name+"','"+author+"','"+publisher+"','"+catagory+"','"+language+"','"+price+"','"+quant+"')";
                    int a=st.executeUpdate(m);
                    if (a>0) {
                         String im="SELECT `bname`,`author`,`publisher`,`catagory`,`language`,`price`,`quantity` FROM `book`";
                        showData(im);
                        JOptionPane.showMessageDialog(this, "Added sucessfull");
                        
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Added failed");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(BookOperation.class.getName()).log(Level.SEVERE, null, ex);
                }
                 
             
             
             }
         
               
        
        
      
       
        
        
        
        
        
        
        
        
        
        
            
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtcatagoryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcatagoryKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           
           
        }
            
    }//GEN-LAST:event_txtcatagoryKeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            // TODO add your handling code here:
            String cat=txtcatagory.getSelectedItem().toString();
            Myconnect();
            String mm="INSERT INTO `book_catagory`(`catagory`) VALUES ('"+cat+"')";
            int a=st.executeUpdate(mm);
            if(a>0){
              //txtcatagory.removeAllItems();
              datashowCombo();
                //JOptionPane.showMessageDialog(this, "Catagory added");
                txtcatagory.setSelectedItem(cat);
            }
                    
        } catch (SQLException ex) {
            Logger.getLogger(BookOperation.class.getName()).log(Level.SEVERE, null, ex);
        }
      
                 
          
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookOperation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField txtauthor;
    private javax.swing.JTextField txtbid;
    private javax.swing.JComboBox txtcatagory;
    private javax.swing.JComboBox txtlanguage;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtpublisher;
    private javax.swing.JTextField txtquant;
    // End of variables declaration//GEN-END:variables

}
